### ISSUE TITLE
HTML User Name Page (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#10]
## User story
AS A player of the game
I WANT to be able to enter my name
SO THAT I know whose selections are whose and I know who wins

## Tasks
- [x] section tag containing all below with id=username-page
- [x] form element exists with id=username-form
- [x] form element contains 2 text inputs
- [x] form element contains a submit button with id=submit-button

**Comment by LoganLagrange** [comment]
materialize elements needed
