### ISSUE TITLE
Clone Repo Locally (CLI, GitHub)

### ISSUE THREAD

**Issue by Spec-Tr** [DavidRodriguez119/Movie-Selector-Game#11]
## User Story
AS A software developer & remote collaborator in-training
I WANT to be able to access and work on the code safely, without jeopardizing the main branch
SO THAT I can learn to code without damaging any good work our group has already done

## Tasks
- [x] Clone Repo Locally
- [x] Create Dev branch
- [x] Create individual collaborator-feature branches (ongoing)
