### ISSUE TITLE
HTML Genre page (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#13]
## User Story
AS A player of the game
I WANT to be able to choose from a list of genres for my movie
SO THAT i can get a suggestion from a genre that i like

## Tasks
- [x] select element exists with id=genre-form
- [x] select element contains 2 dropdown menus (1 for each player) with respective ids
- [x] select element contains submit button with id=genre-submit-button

**Comment by LoganLagrange** [comment]
materialize elements needed
