### ISSUE TITLE
Draw Card Click (JS - 6)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#14]
## User Story
AS A user whose turn is to play
I WANT to draw a card 
SO THAT I can play the card game

## Tasks
- [x] Add a click event listener for the deck of cards image
- [x] When the deck of cards is pressed for the first time select a random card
- [x] Assign the card to a variable Name: cardUser1
- [x] Display the image of the card that was assigned for user1
- [x] Change any HTML required to let user2 know its their turn
- [x] When the deck of cards is pressed for the second time select a random card
- [x] Assign the card to a variable Name: cardUser2
- [x] Display the image of the card that was assigned for user2
- [x] Once the Deck of cards have been pressed twice, block the click event listener
- [x] Once the Deck of cards have been pressed twice, hide the HTML elements that correspond to the game page
- [x] Display the win-page
