### ISSUE TITLE
HTML Plot Picker Page (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#15]
## User Story
AS A player in the game
I WANT to choose from a list of plots to choose my movie
SO THAT i can have a prize for winning the game

## Tasks
- [x] section tag containing all below with id=plot-picker-page
- [x] form tag exists with id=plot-picker-p1
- [x] form tag exists with id=plot-picker-p2
- [x] both form tags contain checkboxes with movie plots
- [x] button tag exists "play game" with id=plot-picker-button
