### ISSUE TITLE
HTML win page (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#17]
## User Story
AS A player of the game
I WANT to see the  winner of the game
SO THAT we can watch their movie  and get some information about it

## Tasks
- [x] section tag exists containing all below with id=win-page
- [x] h2 exists with id=winner-h2
- [x] h3 exists "Tonight's Movie is: (winner)"
- [x] h3 exists with id=winning-movie
- [x] img tag exists with id=movie-poster
- [x] p tag exists with id=winning-movie-info
- [x] button element exists "play again" with id=again-button
