### ISSUE TITLE
Genre Selector Button (JS - 4)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#18]
## User Story
AS A player of the game
I WANT to select a movie genre 
SO THAT I can pick a movie of my liking 

## Tasks
- [x] add a click event listener for the selectGenreBtn
- [x] When the sselectGenreBtn is pressed, the users' input is validated to check the two genres where selected
- [x] Display an alert if the users didn't enter one or both movie genres
- [x] Within user1 and user2 objects, store the selected genre under variables called: genreSelected
- [x] the HTML elements for this page are hidden
- [x] the HTML elements for the plot-picker-page are displayed
