### ISSUE TITLE
Plot-Picker-Button (JS - 5)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#19]
## User Story
AS A player of the game
I WANT to select a movie plot based on the genre I selected
SO THAT I can be ready to play

## Tasks
- [x] add a click event listener for the plotPickerBtn
- [x] When the plotPickerBtn is pressed, the users' input is validated to verify that one checkbox for each user was selected
- [x] Display an alert if the users didn't check any of the corresponding checkboxes
- [x] Within user1 and user2 objects, store the selected plots under variables called plotSelected
- [x] the HTML elements for this page are hidden
- [x] the HTML elements for the game page are displayed
