### ISSUE TITLE
Reset Button (JS - 7)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#20]
## User Story
AS A user who finished the cards game
I WANT to be able to play again
SO THAT I can select a different movie

## Tasks
- [x] Add a click event listener for the resetBtn
- [x] When the resetBtn is pressed, hide the HTML elements that correspond to the results page
- [x] Display the initial page
- [x] Change played variables to false
