### ISSUE TITLE
Movies Fetch (JS)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#24]
## User Story
AS A developer of this app
I WANT to store all the movies information under a single object
SO THAT I can easily utilize the data

## Tasks
- [x] create a movies object. Name: movies
- [x] within the movies object create three empty objects with the following names: animation, horror, action
- [x] fetch the information of five horror movies
- [x] fetch the information of five animated movies
- [x] fetch the information of five action movies
