### ISSUE TITLE
Display genre options in select menus

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#31]
## User Story
AS A player of the game
I WANT to see the genre options displayed in the  dropdown menus
SO THAT i can select one

## Tasks
- [x] grab select menus using id select
- [x] create for loop to loop over select menus
- [x] create new option tag within it
- [x] display genre from movies array in option tag

**Comment by LoganLagrange** [comment]
Ended up using a for in loop
