### ISSUE TITLE
Basic CSS Styles (CSS-1)

### ISSUE THREAD

**Issue by Spec-Tr** [DavidRodriguez119/Movie-Selector-Game#4]
## User Story
AS A player of the card game movie decider game
I WANT clear, concise, modern styling
SO THAT I enjoy the appearance of the website

## Tasks
- [x] Select colour scheme: Background colour, card colours, text colour
- [x] Select font-family
- [x] Select Card style appearance
