### ISSUE TITLE
Add headers to sections (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#40]
## User Story
AS A player of the game
I WANT to see a header on the cards
SO THAT i can understand what to do on the page

## Tasks
- [x] Add clear headers to the sections explaining what do on the card
- [x] Add classes to dynamically updated headers with usernames
- [x] Create function for usernames to update in headers
