### ISSUE TITLE
Theme-Related Card Appearance (CSS)

### ISSUE THREAD

**Issue by Spec-Tr** [DavidRodriguez119/Movie-Selector-Game#42]
## User Story
AS A player of the game
I WANT the appearance to be related to the themes involved with the game
SO THAT The game feels more integral and cohesive

## Tasks
- [x] find theatre themed border
- [x] find card/betting table themed border
- [x] find generic themed border
- [x] apply to respectively themed cards
