### ISSUE TITLE
Card-Reverse Images

### ISSUE THREAD

**Issue by Spec-Tr** [DavidRodriguez119/Movie-Selector-Game#43]
## User Story
AS A player of the game
I WANT the page to visually represent what playing this card game in real life would look like
SO THAT it feels authentic and immersive

## Tasks
- [x] Acquire card reverse image
- [x] place card reverse images on page
- [x] position and label/header card reverse images so that ownership (P1 v. P2) is clear
