### ISSUE TITLE
War Card Game (MVP)

### ISSUE THREAD

**Issue by Spec-Tr** [DavidRodriguez119/Movie-Selector-Game#44]
## User Story
AS A user of the movie picker card game
I WANT a simple chance-based card game to determine whose movie selection will be picked for movie night
SO THAT a movie can be fairly selected for movie night without bias

## Tasks
- [x] Assign numerical values to card IDs
- [x] build functionality to draw a random card for both players
- [x] build functionality to compare card number values and determine the greater of the two, or play again in a tie game
- [x] display 'next page' button when a winner has been determined
