### ISSUE TITLE
Blackjack (21) Card Game - Feature

### ISSUE THREAD

**Issue by Spec-Tr** [DavidRodriguez119/Movie-Selector-Game#45]
## User Story
AS A player of the game
I WANT to have the winner determined by a slightly more complex card game than in MVP
SO THAT the game requires more strategy and is therefore more rewarding to win

## Tasks
- [ ] Build functionality to store (obdurate) player card values
- [ ] Build functionality to draw multiple cards (create  a 'current hand' container?)
- [ ] Build functionality to set win condition as highest player card value ≤ 21
