### ISSUE TITLE
Validate Checkboxes

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#50]
## User Story
AS A user of the app
I WANT to be able to pick only one movie  
SO THAT if I accidentally cross more than one checkbox the app instructs me to correct my mistake

## Tasks
- [x] when the play game Button is pressed the program checks that each player has picked a checkbox
- [x] add a count variable to identify the number of checkboxes picked by each player
- [x] enclose the code in an if statement
- [x] if the count is greater than one for any of the users alert to make a change

**Comment by LoganLagrange** [comment]
ended up changing checkboxes to radio boxes in a group which solved the potential issue
