### ISSUE TITLE
Ties (JS)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#52]
## User Story
AS A user of this app that draw the same card as my opponent
I WANT to be able to play again
SO THAT we can pick a movie

## Tasks
- [x] inform the user when there is a draw
- [x] clear the variables' values
- [x] restart the game
