### ISSUE TITLE
Display winning movie on game page

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#54]
## User Story
AS A player of the game
I WANT to see which movie won
SO THAT i can watch it

## Tasks
- [x] Display winning movie in winning-movie header
- [x] Display winning player in winner-h2 header
- [x] Display winning poster in movie-poster img
- [x] Create list of info about the movie
- [x] Create, fill, and append info to the list

**Comment by LoganLagrange** [comment]
Ended up using a p tag and presenting additional info as a fun fact
