### ISSUE TITLE
HTML Skeleton (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#6]
## User Story
AS A developer on the project
I WANT a basic skeleton of the HTML document
SO THAT I have something to work from

## Tasks
- [x] Basic boilerplate
- [x] Link in stylesheets & script tags
- [x] Create header for title
- [x] Main tag exists
