### ISSUE TITLE
Start Button (JS - 2)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#7]
## User Story
AS A person who wants to select a movie
I WANT to start the application after reading the instructions
SO THAT I can start with the game

## Tasks
- [x] add a click event listener for the start Btn
- [x] when the start Btn is pressed all the HTML involving the start page is hidden
- [x] the HTML elements for the enter username-page are displayed
