### ISSUE TITLE
Alerts to Modals

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#76]
## User Story
AS A user of this app
I WANT to be informed if I use the page incorrectly
SO THAT I am alerted with Modals about my mistake

## Tasks:
- [x] Change the alert in the usernames page to a modal
- [x] Change the alert in the genre page to a modal
- [x] Change the alert in the plots page to a modal
