### ISSUE TITLE
HTML Landing Page (HTML)

### ISSUE THREAD

**Issue by LoganLagrange** [DavidRodriguez119/Movie-Selector-Game#8]
## User Story
AS AN indecisive movie fan
I WANT to see the instructions and a button to start the game
SO THAT i can understand the game and start it

## Tasks
- [x] section tag containing all below with id=landing-page
- [x] <p tag exists 
- [x] <p tag contains welcome and instructions
- [x] <button tag exists with id=start-button
