### ISSUE TITLE
Enter User Button (JS - 3)

### ISSUE THREAD

**Issue by DavidRodriguez119** [DavidRodriguez119/Movie-Selector-Game#9]
## User Story
AS A user who wants to have all my data under my name
I WANT to save my username 
SO THAT I can easily understand the game results

## Tasks
- [x] Add a click event listener for the Usernames form's button
- [x] When the button is pressed the two usernames are validated to check that they contain text
- [x] Display an alert if the user(s) haven't enter any usernames
- [x] Save each user name within the users objects under the variable username
- [x] Hide all the HTML related to the username-page
- [x] Display the HTML related to the genre-page
